@(current-here (symbol->string here))
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>@(extract-metas 'title)</title>
    <meta name="author"      content="Sorawee Porncharoenwase">
    <meta name="keywords"    content="<!-- TODO -->">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <link rel="icon"      href="@|path-prefix|favicon.ico">
    <link rel="canonical" href="<!-- TODO -->">

    <!-- TODO -->
    @;{
    @(when rel-next @list{<link rel="next" href="@|rel-next|">})
    @(when rel-prev @list{<link rel="prev" href="@|rel-prev|">})
    }

    <!-- CSS -->
    <link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">
    <link rel="stylesheet" href="https://afeld.github.io/emoji-css/emoji.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="@|path-prefix|css/app.css">
    <link rel="stylesheet" type="text/css" href="@|path-prefix|css/pygments.css">
    <link rel="stylesheet" type="text/css" href="@|path-prefix|css/scribble.css">

    <!-- TODO: Feeds -->
    @;{
    <link rel="alternate" type="application/atom+xml"
          href="@|atom-feed-uri|" title="Atom Feed">
    <link rel="alternate" type="application/rss+xml"
          href="@|rss-feed-uri|" title="RSS Feed">
    }
    <!-- TODO: Google Analytics -->
  </head>
  <body>

    <!-- A standard Twitter Bootstrap nav bar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <div class="navbar-brand site-info">
          <h1>
            <a href="@|path-prefix|index.html">Sorawee Porncharoenwase</a>
          </h1>
          <p>PhD Student at UW CSE</p>
        </div>

        <button class="navbar-toggler navbar-toggler-right"
                type="button" data-toggle="collapse"
                data-target="#navbar_collapse" aria-controls="navbar_collapse"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar_collapse">
          @(->html `(ul ([class "navbar-nav ml-auto"])
                      ,(navbar-link "index.html" "Home")
                      ,(navbar-link "blog" "Blog")
                      ,(navbar-icon
                        "mailto:sorawee@cs.washington.edu"
                        "sorawee@cs.washington.edu"
                        "fas fa-envelope")
                      ,(navbar-icon
                        (string-append "https://norfolk.cs.washington.edu/"
                                       "directory/index.php?"
                                       "prev_floor=3&show_room=CSE394")
                        "CSE 394"
                        "fas fa-map-marker-alt")
                      ,(navbar-icon
                        "https://www.github.com/sorawee"
                        "@sorawee"
                        "fab fa-github")
                      ,(navbar-view-source)))
        </div>
      </div>
    </nav>

    <main class="container">
      <div id="content-title--@(slug here)"
           class="row content-type--@(symbol->string (get-meta-type))">
        <!-- Main column -->
        <div>@(->html (main-content))</div>
      </div>
      <footer>
        <hr />
        <div class="float-md-left">
          Site generated by <a href="http://pollenpub.com">
            Pollen
          </a>/<a href="https://racket-lang.org">
            Racket
          </a>
        </div>
        <div class="float-md-right">
          © Sorawee Porncharoenwase
        </div>
      </footer>
    </main>
    <!-- JS -->
    <script type="text/javascript" src="@|path-prefix|js/jquery-3.2.1.slim.min.js"></script>
    <script type="text/javascript" src="@|path-prefix|js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    <script type="text/javascript" src="@|path-prefix|js/script.js"></script>
  </body>
</html>
